# Referencing variables:
# https://www.serverless.com/framework/docs/providers/aws/guide/variables/

service: piupiu

provider:
  name: aws
  logs:
    websocket: true
  region: eu-north-1
  runtime: nodejs14.x
  websocketsApiName: piupiu-api
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  lambdaHashingVersion: 20201221
  iam:
    logRole:
      name: log-role
      path: /log-role/
      statements:
        - Effect: Allow
          Resource: arn:aws:logs:*:*:*
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
    dynamoRole:
      name: dynamo-role
      path: /dynamo-role/
      statements:
        - Effect: Allow
          Resource: !GetAtt LobbyTable.Arn
          # Resource: 'arn:aws:dynamodb:eu-north-1:*:*'
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem

functions:
  connectionHandler:
    handler: server.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: server.defaultHandler
    events:
      - websocket: $default #simple event definition without extra route property
  customFooHandler:
    handler: server.fooHandler
    events:
      - websocket:
          route: foo # will trigger if $request.body.action === "foo"

resources:
  Resources:
    lobbyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lobbyTable
        AttributeDefinitions:
          - AttributeName: joinCode
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
